import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// class HomePageProps {
//   name: string;
//   constructor(name: string){
//     this.name = name;
//   }
// }

export default function Home({
  categories,
}: {
  categories: {
    code: string;
    name: string;
    seuence: string;
  }[];
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>iSnatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to iSnatch!</h1>

        <p className={styles.description}>
          Get ready to snatch cash back :)
        </p>
        <ul>
            {categories.map(({ code, name }) => (
              <li key={code}>{name}</li>
            ))}
          </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/zamanhasib/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Hasib
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(process.env.REACT_APP_API_URL + "categories/");
  const categories = await res.json();
  console.log(categories);
  return { props: { categories } };
};
