import { FC } from "react";
import NextHead from "next/head";

const Head: FC = () => {
  return (
    <>
      <NextHead>
        <title>iSnatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </NextHead>
    </>
  );
};

export default Head;
